server:
    port: 9000
spring:
    profiles:
      active : development
---
spring:
  profiles: development
  datasource:
    url : jdbc:mysql://localhost:3306/db_example
    username : springuser
    password : r0ys1ngh4m

  jpa:
    hibernate:
      ddl-auto : create
---
spring:
  profiles: test

---
spring:
  profiles: prod
  datasource:
    url : jdbc:mysql://mysql/db_example
    username : springuser
    password : r0ys1ngh4m

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto : none
      dialect  : org.hibernate.dialect.MySQL5InnoDBDialect

